Backend3/Backend3/Models/ErrorViewModel.cs
namespace Backend3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Backend3/Backend3/Models/QuizModel.cs
namespace Backend3.Models
{
    public class QuizModel
    {
        public OrderedDictionary<string, string> Questions { get; private set; }
        public List<UserQuestionResponse> UserResponse { get; private set; }
        public List<UserQuestionResponse> PreviousUserResponse { get; private set; }

        public int CurrentQuestionIndex = 0;

        public QuizModel()
        {
            Questions = new OrderedDictionary<string, string>()
            {
                {"1 - 6", "-5"},
                {"8 + 6", "14"},
                {"5 - 7", "-2"},
                {"5 - 2", "3"}
            };

            UserResponse = new List<UserQuestionResponse>();
            PreviousUserResponse = new List<UserQuestionResponse>();
        }

        public void Reset()
        {
            PreviousUserResponse.Clear();
            foreach (var item in UserResponse)
            {
                PreviousUserResponse.Add(item);
            }
            UserResponse.Clear();
            CurrentQuestionIndex = 0;
        }
    }
}

Backend3/Backend3/Models/UserQuestionResponse.cs
using System.ComponentModel.DataAnnotations;

namespace Backend3.Models
{
    public class UserQuestionResponse
    {
        [Required]
        public string? Response { get; set; } = null;

    }
}

Backend3/Backend3/Controllers/HomeController.cs
using System.Diagnostics;
using Backend3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Backend3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Backend3/Backend3/Controllers/MockupsController.cs
using Microsoft.AspNetCore.Mvc;
using Backend3.Models;


namespace Backend3.Controllers
{
    public class MockupsController : Controller
    {
        private QuizModel _quiz;
        private UserQuestionResponse _questionResponse;

        public MockupsController(QuizModel model, UserQuestionResponse questionResponse)
        {
            _quiz = model;
            _questionResponse = questionResponse;
        }

        [HttpGet]
        public IActionResult Quiz()
        {
            int questionIndex = _quiz.CurrentQuestionIndex;
            ViewBag.Question = _quiz.Questions.ElementAt(questionIndex).Key;
            
            return View();
        }

        [HttpPost]
        public IActionResult Quiz(UserQuestionResponse userResponse, string action)
        {
            if(!ModelState.IsValid)
            {
                userResponse.Response = "Ответа нет";
            }

            _quiz.UserResponse.Add(userResponse);
            int questionNumber = ++_quiz.CurrentQuestionIndex;

            if (action == "Next" && questionNumber < _quiz.Questions.Count)
            {
                ViewBag.Question = _quiz.Questions.ElementAt(questionNumber).Key;
            }
            else
            {
                for(int i = questionNumber; i < _quiz.Questions.Count; i++)
                {
                    UserQuestionResponse newUserResponse = new UserQuestionResponse();
                    newUserResponse.Response = "Ответа нет";
                    _quiz.UserResponse.Add(newUserResponse);
                }
                CalculateResult(_quiz.UserResponse);
                
                _quiz.Reset();
                return View();
            }

            return View();
        }

        public IActionResult ShowPreviousResult()
        {
            if(_quiz.PreviousUserResponse.Count == 0)
            {
                int questionIndex = _quiz.CurrentQuestionIndex;
                ViewBag.Question = _quiz.Questions.ElementAt(questionIndex).Key;

                return View("Quiz");
            }
            CalculateResult(_quiz.PreviousUserResponse);
            return View("Quiz");
        }

        private void CalculateResult(List<UserQuestionResponse> userAnswer)
        {
            int correctAnswersCount = 0;
            string[] results = new string[_quiz.Questions.Count];

            for (int i = 0; i < _quiz.Questions.Count; i++)
            {
                var question = _quiz.Questions.ElementAt(i).Key;
                var answer = _quiz.Questions.ElementAt(i).Value;

                if (userAnswer[i].Response == answer)
                    correctAnswersCount++;

                results[i] = $"{i+1}. {question} = {userAnswer[i].Response}";
            }

            ViewBag.QuestionCount = _quiz.Questions.Count;
            ViewBag.CorrectAnswersCount = correctAnswersCount;
            ViewBag.Results = results;

            return;
        }

    }
}

Backend3/Backend3/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<h1>Mockups</h1>
<ul>
	<li>
		<a asp-controller="Mockups" asp-action="Quiz">Quiz</a>
		
	</li>
	<li>
		<a asp-controller="Mockups" asp-action="ShowPreviousResult">QuizResult</a>
	</li>
</ul>

Backend3/Backend3/Views/Mockups/Quiz.cshtml
@{
	ViewBag.Title = "Hello Quiz";
}



@if (ViewBag.Results is null)
{
	<h2>Quiz</h2>
	<div class="col-md-3">
		<form action="@Url.Action("Quiz", "Mockups")" method="post">
			<label>@ViewBag.Question</label>
			<input class="form-control" type="text" name="Response" />

			<div class="mt-2">
				<input class="btn btn-outline-dark" type="submit" name="action" value="Next" />
				<input class="btn btn-primary" type="submit" name="action" value="Finish" />
			</div>

		</form>
	</div>

}
else
{
	<h2>Quiz results</h2>
	<h4>Right answers @ViewBag.CorrectAnswersCount out @ViewBag.QuestionCount</h4>

	<p class="ms-4">
		@foreach (var result in ViewBag.Results)
		{
			@result<br>
		}
	</p>

}

Backend3/Backend3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Backend3</title>
	<script type="importmap"></script>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Backend3.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom border-dark box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Backend3</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Mockups</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<div class="container">
		<footer class="border-top text-muted">
			<div class="mt-3">
				&copy; 2024 - Backend3
			</div>
		</footer>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>